# Generated by Django 5.0.14 on 2025-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
