# Generated by Django 5.0.14 on 2025-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_alter_statementitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementitem',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
