# Generated by Django 5.0.14 on 2025-05-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_statementitem_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('account', 'date')},
        ),
    ]
